"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import {
  Avatar,
  Box,
  Button,
  Flex,
  Image,
  SimpleGrid,
  Spacer,
  Text,
} from "@chakra-ui/react";
import { IoIosMenu, IoIosNotificationsOutline } from "react-icons/io";
import { CiSearch } from "react-icons/ci";
import { RiMenu2Line } from "react-icons/ri";
import { Toaster } from "@/components/ui/toaster";
import { useEffect, useState } from "react";
import { attrBorderGrey, attrBorderGrey2 } from "@/color";
import { MdOutlineKeyboardArrowRight } from "react-icons/md";
import { Chart as ChartJS, registerables } from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";
import annotationPlugin from "chartjs-plugin-annotation";
import { recruitmentMenuList } from "./global-data";
ChartJS.register(...registerables, ChartDataLabels, annotationPlugin);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const plusMenuList = [
  {
    title: "취업 ・ 이직",
    list: [
      "경력 정보 불러오기",
      "면접 코칭받기",
      "내 커리어 리포트 보기",
      "추천사 작성/요청하기",
      "챗봇으로 포지션 찾기",
    ],
  },
  {
    title: "혜택 ・ 정보",
    list: [
      "디벨로퍼 포인트",
      "직군별 연봉",
      "최신 채용 트렌드",
      "최신 기술 트렌드",
    ],
  },
  { title: "인사 담당자", list: ["HR 커뮤니티 인살롱", "HR 솔루션"] },
  { title: "교육 담당자", list: ["디벨로퍼 취업지원시스템"] },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuHoverState, setIsMenuHoverState] = useState<string | null>(null);

  useEffect(() => {
    if (menuHoverState) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "scroll";
    }
  }, [menuHoverState]);

  const RecruitmentHoverMenu = () => {
    const [curMenu, setCurMenu] = useState("all");

    return (
      <Box w="100%" h="250px" bg="grey">
        <Flex h="250px">
          <Box
            bg="white"
            flex={3}
            textAlign="center"
            maxH="250px"
            overflow="hidden"
          >
            {Object.entries(recruitmentMenuList).map((v: any, index) => {
              return (
                <Text
                  key={index}
                  fontSize={14}
                  mt={3}
                  mb={3}
                  fontWeight={v[0] === "all" ? "bold" : "normal"}
                  color="#323232"
                  _hover={{ fontWeight: "bold", color: "black" }}
                  onMouseEnter={() => {
                    setCurMenu(v[0]);
                  }}
                >
                  {v[1].title}
                </Text>
              );
            })}
          </Box>

          <Box borderLeft={attrBorderGrey} />

          <Box
            bg="white"
            flex={7}
            alignContent={curMenu === "all" ? "center" : "start"}
          >
            {curMenu === "all" ? (
              <Text textAlign="center" color="grey" fontSize={14}>
                직군을 먼저 선택하면 상세 직무를 볼 수 있어요.
              </Text>
            ) : (
              <SimpleGrid
                columns={3}
                maxH="250px"
                overflow="auto"
                pt="24px"
                pb="24px"
                gapY="12px"
              >
                {recruitmentMenuList[curMenu].list.map(
                  (v: any, index: number) => {
                    return (
                      <Box key={index} pl={4} h={30} alignItems="top">
                        <Text
                          fontSize={14}
                          _hover={{ fontWeight: "bold", color: "black" }}
                        >
                          {v}
                        </Text>
                      </Box>
                    );
                  }
                )}
              </SimpleGrid>
            )}
          </Box>
        </Flex>
      </Box>
    );
  };

  const PlusHoverMenu = () => {
    return (
      <SimpleGrid
        columns={5}
        maxH="300px"
        w="100%"
        bg="white"
        overflow="auto"
        pt="24px"
        pb="24px"
      >
        {plusMenuList.map((v, index) => {
          return (
            <Box key={index} ml={8}>
              <Text fontWeight="bold" mb="24px">
                {v.title}
              </Text>
              {v.list.map((v, index) => {
                return (
                  <Text
                    key={index}
                    fontSize={14}
                    mb={4}
                    _hover={{ fontWeight: "bold" }}
                  >
                    {v}
                  </Text>
                );
              })}
            </Box>
          );
        })}

        <Box w="200px" h="100%" borderRadius="10px" bg="#303030" p="16px">
          <Text color="white" fontWeight="bold" whiteSpace="pre-line">
            {`커리어를 
                  쌓으면 포인트가 쌓여요.`}
          </Text>

          <Flex>
            <Text fontSize={14} color="#0095ff" fontWeight="bold">
              포인트 확인하기
            </Text>

            <Box mb="1px">
              <MdOutlineKeyboardArrowRight color="#0095ff" size={20} />
            </Box>
          </Flex>

          <Image src="/savings.png" w="120px" mt="25px" ml="20px" />
        </Box>
      </SimpleGrid>
    );
  };

  const Header = () => {
    return (
      <Box position="fixed" top={0} zIndex={1024} width="100%">
        <Flex
          backgroundColor="white"
          height="59px"
          alignItems="center"
          pl="20px"
          pr="20px"
          borderBottom={attrBorderGrey2}
        >
          <Image
            height="35px"
            src="/developer_logo_horizon.png"
            onMouseEnter={() => {
              setIsMenuHoverState(null);
            }}
          />

          <Box className="hidden md:block">
            <Flex gap={8}>
              <Flex
                ml={8}
                alignItems="center"
                className="hover:text-purple-400"
                onMouseEnter={() => {
                  setIsMenuHoverState("recruitment");
                }}
              >
                <RiMenu2Line size={20} />
                <Text fontSize={14} ml="4px" fontWeight="semibold">
                  채용
                </Text>
              </Flex>

              <Text
                className="hover:text-purple-400"
                fontSize={14}
                fontWeight="semibold"
                onMouseEnter={() => {
                  setIsMenuHoverState(null);
                }}
              >
                커리어
              </Text>

              <Text
                className="hover:text-purple-400"
                fontSize={14}
                fontWeight="semibold"
                onMouseEnter={() => {
                  setIsMenuHoverState(null);
                }}
              >
                소셜
              </Text>

              <Text
                className="hover:text-purple-400"
                fontSize={14}
                fontWeight="semibold"
                onMouseEnter={() => {
                  setIsMenuHoverState(null);
                }}
              >
                이력서
              </Text>

              <Text
                className="hover:text-purple-400"
                fontSize={14}
                fontWeight="semibold"
                onMouseEnter={() => {
                  setIsMenuHoverState(null);
                }}
              >
                프리랜서
              </Text>

              <Text
                className="hover:text-purple-400"
                fontSize={14}
                fontWeight="semibold"
                onMouseEnter={() => {
                  setIsMenuHoverState("plus");
                }}
              >
                더보기
              </Text>
            </Flex>
          </Box>

          <Spacer />
          <Flex alignItems="center" gap={1}>
            <CiSearch
              size={30}
              className="hover:text-purple-400"
              onMouseEnter={() => {
                setIsMenuHoverState(null);
              }}
            />
            <IoIosNotificationsOutline
              size={30}
              className="hover:text-purple-400"
              onMouseEnter={() => {
                setIsMenuHoverState(null);
              }}
            />

            <Box className="hidden lg:block">
              <Avatar.Root
                colorPalette="blue"
                size="sm"
                className="hover:scale-105 ease-in-out"
                onMouseEnter={() => {
                  setIsMenuHoverState(null);
                }}
              >
                <Avatar.Fallback />
                <Avatar.Image src="https://bit.ly/broken-link" />
              </Avatar.Root>
            </Box>

            <Box className="block lg:hidden">
              <IoIosMenu size={30} className="hover:text-purple-400" />
            </Box>

            <Box
              className="hidden lg:block"
              onMouseEnter={() => {
                setIsMenuHoverState(null);
              }}
            >
              <Button variant="outline" borderRadius={12} size="sm" ml={4}>
                기업 서비스
              </Button>
            </Box>
          </Flex>
        </Flex>

        {menuHoverState === "recruitment" && <RecruitmentHoverMenu />}
        {menuHoverState === "plus" && <PlusHoverMenu />}
      </Box>
    );
  };

  const naverMapSrc = `https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_MAP_CLIENT_ID}`;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {/* 상단 탭바 */}
          <Box mb="59px">
            <Header />
          </Box>

          {/* 메뉴 오버레이 */}
          {menuHoverState && (
            <Box
              w="100%"
              h="100%"
              bg="rgba(0, 0, 0, 0.5)"
              position="fixed"
              top={0}
              zIndex={1023}
              onMouseEnter={() => {
                setIsMenuHoverState(null);
              }}
            />
          )}

          <Toaster />
          {children}
        </Provider>

        <script type="text/javascript" src={naverMapSrc} />
      </body>
    </html>
  );
}
